name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u "k0nova" --password-stdin
        docker image build -t k0nova/g_action:latest .
        docker push k0nova/g_action:latest
