name: Static Page

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "k0nova" --password-stdin
        docker image build -t k0nova/g_action:latest .
        docker push k0nova/g_action:latest
